apiVersion: v1
kind: Pod
metadata:
  name: dataaccess-beir
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data-beir-evaluation
          mountPath: /data
  volumes:
    - name: data-beir-evaluation
      persistentVolumeClaim:
        claimName: data-beir-evaluation
